# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\trpc.proto\x12\x05proto\"&\n\tNumerical\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\"(\n\x0b\x43\x61tegorical\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t\" \n\x03Raw\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x82\x01\n\x0bMeasurement\x12%\n\tnumerical\x18\x01 \x01(\x0b\x32\x10.proto.NumericalH\x00\x12)\n\x0b\x63\x61tegorical\x18\x02 \x01(\x0b\x32\x12.proto.CategoricalH\x00\x12\x19\n\x03raw\x18\x03 \x01(\x0b\x32\n.proto.RawH\x00\x42\x06\n\x04type\"K\n\x12MeasurementMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x0bmeasurement\x18\x02 \x01(\x0b\x32\x12.proto.Measurement\"L\n\x0fRetrieveRequest\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\x1d\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\r.proto.Filter\";\n\x0fMeasurementList\x12(\n\x0cmeasurements\x18\x01 \x03(\x0b\x32\x12.proto.Measurement\"\x97\x01\n\x10RetrieveResponse\x12\x39\n\thistories\x18\x01 \x03(\x0b\x32&.proto.RetrieveResponse.HistoriesEntry\x1aH\n\x0eHistoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.proto.MeasurementList:\x02\x38\x01\"2\n\x06\x46ilter\x12\x19\n\x11granularity_nanos\x18\x01 \x01(\x03\x12\r\n\x05names\x18\x02 \x03(\t\"\t\n\x07Nothing2\xed\x01\n\x05Mhist\x12\x32\n\x05Store\x12\x19.proto.MeasurementMessage\x1a\x0e.proto.Nothing\x12:\n\x0bStoreStream\x12\x19.proto.MeasurementMessage\x1a\x0e.proto.Nothing(\x01\x12;\n\x08Retrieve\x12\x16.proto.RetrieveRequest\x1a\x17.proto.RetrieveResponse\x12\x37\n\tSubscribe\x12\r.proto.Filter\x1a\x19.proto.MeasurementMessage0\x01\x62\x06proto3')
)




_NUMERICAL = _descriptor.Descriptor(
  name='Numerical',
  full_name='proto.Numerical',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='proto.Numerical.ts', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Numerical.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=58,
)


_CATEGORICAL = _descriptor.Descriptor(
  name='Categorical',
  full_name='proto.Categorical',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='proto.Categorical.ts', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Categorical.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=100,
)


_RAW = _descriptor.Descriptor(
  name='Raw',
  full_name='proto.Raw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='proto.Raw.ts', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Raw.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=134,
)


_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='proto.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numerical', full_name='proto.Measurement.numerical', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categorical', full_name='proto.Measurement.categorical', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw', full_name='proto.Measurement.raw', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='proto.Measurement.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=137,
  serialized_end=267,
)


_MEASUREMENTMESSAGE = _descriptor.Descriptor(
  name='MeasurementMessage',
  full_name='proto.MeasurementMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.MeasurementMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement', full_name='proto.MeasurementMessage.measurement', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=344,
)


_RETRIEVEREQUEST = _descriptor.Descriptor(
  name='RetrieveRequest',
  full_name='proto.RetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='proto.RetrieveRequest.start', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='proto.RetrieveRequest.end', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter', full_name='proto.RetrieveRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=422,
)


_MEASUREMENTLIST = _descriptor.Descriptor(
  name='MeasurementList',
  full_name='proto.MeasurementList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurements', full_name='proto.MeasurementList.measurements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=483,
)


_RETRIEVERESPONSE_HISTORIESENTRY = _descriptor.Descriptor(
  name='HistoriesEntry',
  full_name='proto.RetrieveResponse.HistoriesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.RetrieveResponse.HistoriesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.RetrieveResponse.HistoriesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=637,
)

_RETRIEVERESPONSE = _descriptor.Descriptor(
  name='RetrieveResponse',
  full_name='proto.RetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='histories', full_name='proto.RetrieveResponse.histories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RETRIEVERESPONSE_HISTORIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=637,
)


_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='proto.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='granularity_nanos', full_name='proto.Filter.granularity_nanos', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='names', full_name='proto.Filter.names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=689,
)


_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='proto.Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=700,
)

_MEASUREMENT.fields_by_name['numerical'].message_type = _NUMERICAL
_MEASUREMENT.fields_by_name['categorical'].message_type = _CATEGORICAL
_MEASUREMENT.fields_by_name['raw'].message_type = _RAW
_MEASUREMENT.oneofs_by_name['type'].fields.append(
  _MEASUREMENT.fields_by_name['numerical'])
_MEASUREMENT.fields_by_name['numerical'].containing_oneof = _MEASUREMENT.oneofs_by_name['type']
_MEASUREMENT.oneofs_by_name['type'].fields.append(
  _MEASUREMENT.fields_by_name['categorical'])
_MEASUREMENT.fields_by_name['categorical'].containing_oneof = _MEASUREMENT.oneofs_by_name['type']
_MEASUREMENT.oneofs_by_name['type'].fields.append(
  _MEASUREMENT.fields_by_name['raw'])
_MEASUREMENT.fields_by_name['raw'].containing_oneof = _MEASUREMENT.oneofs_by_name['type']
_MEASUREMENTMESSAGE.fields_by_name['measurement'].message_type = _MEASUREMENT
_RETRIEVEREQUEST.fields_by_name['filter'].message_type = _FILTER
_MEASUREMENTLIST.fields_by_name['measurements'].message_type = _MEASUREMENT
_RETRIEVERESPONSE_HISTORIESENTRY.fields_by_name['value'].message_type = _MEASUREMENTLIST
_RETRIEVERESPONSE_HISTORIESENTRY.containing_type = _RETRIEVERESPONSE
_RETRIEVERESPONSE.fields_by_name['histories'].message_type = _RETRIEVERESPONSE_HISTORIESENTRY
DESCRIPTOR.message_types_by_name['Numerical'] = _NUMERICAL
DESCRIPTOR.message_types_by_name['Categorical'] = _CATEGORICAL
DESCRIPTOR.message_types_by_name['Raw'] = _RAW
DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT
DESCRIPTOR.message_types_by_name['MeasurementMessage'] = _MEASUREMENTMESSAGE
DESCRIPTOR.message_types_by_name['RetrieveRequest'] = _RETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['MeasurementList'] = _MEASUREMENTLIST
DESCRIPTOR.message_types_by_name['RetrieveResponse'] = _RETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numerical = _reflection.GeneratedProtocolMessageType('Numerical', (_message.Message,), {
  'DESCRIPTOR' : _NUMERICAL,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.Numerical)
  })
_sym_db.RegisterMessage(Numerical)

Categorical = _reflection.GeneratedProtocolMessageType('Categorical', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORICAL,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.Categorical)
  })
_sym_db.RegisterMessage(Categorical)

Raw = _reflection.GeneratedProtocolMessageType('Raw', (_message.Message,), {
  'DESCRIPTOR' : _RAW,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.Raw)
  })
_sym_db.RegisterMessage(Raw)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENT,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.Measurement)
  })
_sym_db.RegisterMessage(Measurement)

MeasurementMessage = _reflection.GeneratedProtocolMessageType('MeasurementMessage', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTMESSAGE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.MeasurementMessage)
  })
_sym_db.RegisterMessage(MeasurementMessage)

RetrieveRequest = _reflection.GeneratedProtocolMessageType('RetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVEREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.RetrieveRequest)
  })
_sym_db.RegisterMessage(RetrieveRequest)

MeasurementList = _reflection.GeneratedProtocolMessageType('MeasurementList', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTLIST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.MeasurementList)
  })
_sym_db.RegisterMessage(MeasurementList)

RetrieveResponse = _reflection.GeneratedProtocolMessageType('RetrieveResponse', (_message.Message,), {

  'HistoriesEntry' : _reflection.GeneratedProtocolMessageType('HistoriesEntry', (_message.Message,), {
    'DESCRIPTOR' : _RETRIEVERESPONSE_HISTORIESENTRY,
    '__module__' : 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:proto.RetrieveResponse.HistoriesEntry)
    })
  ,
  'DESCRIPTOR' : _RETRIEVERESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.RetrieveResponse)
  })
_sym_db.RegisterMessage(RetrieveResponse)
_sym_db.RegisterMessage(RetrieveResponse.HistoriesEntry)

Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
  'DESCRIPTOR' : _FILTER,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.Filter)
  })
_sym_db.RegisterMessage(Filter)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.Nothing)
  })
_sym_db.RegisterMessage(Nothing)


_RETRIEVERESPONSE_HISTORIESENTRY._options = None

_MHIST = _descriptor.ServiceDescriptor(
  name='Mhist',
  full_name='proto.Mhist',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=703,
  serialized_end=940,
  methods=[
  _descriptor.MethodDescriptor(
    name='Store',
    full_name='proto.Mhist.Store',
    index=0,
    containing_service=None,
    input_type=_MEASUREMENTMESSAGE,
    output_type=_NOTHING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StoreStream',
    full_name='proto.Mhist.StoreStream',
    index=1,
    containing_service=None,
    input_type=_MEASUREMENTMESSAGE,
    output_type=_NOTHING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='proto.Mhist.Retrieve',
    index=2,
    containing_service=None,
    input_type=_RETRIEVEREQUEST,
    output_type=_RETRIEVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='proto.Mhist.Subscribe',
    index=3,
    containing_service=None,
    input_type=_FILTER,
    output_type=_MEASUREMENTMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MHIST)

DESCRIPTOR.services_by_name['Mhist'] = _MHIST

# @@protoc_insertion_point(module_scope)
